name: 'Publish to ESOUI'
description: 'Publishes a package to ESOUI'
author: 'Timothy McLane'
inputs:
  addonId:
    required: true
    description: "Your addon's ID on ESOUI"
  token:
    required: true
    description: 'Your ESOUI authentication token'
  filePath:
    required: true
    description: 'Full path to the addon package for publish'
  version:
    required: true
    description: 'Addon version'
  apiVersions:
    required: true
    description: 'Compatible API version(s) for addon'
runs:
  using: 'node12'
  main: 'dist/index.js'
